#!/bin/bash
list_tables() {
    local _tables=($(tables) "Create Table" "Return to Databases")

    if [[ ${#_tables[@]} -eq 2 ]]; then
        title "$CURRENT_DB"
        loading "No Tables Exist"
    fi

    title "Display Tables: ($CURRENT_DB)"

    print_menu "${_tables[@]}"

    read -p "# " option

    if [[ -z "$option" ]]; then
        loading "No Input Provided";
        list_tables;
        return;
    fi

    index=$(get_index _tables "$option")

    if [[ $index -eq ${#_tables[@]} ]]; then return; fi  
    if (( index == ${#_tables[@]} - 1 )); then  
        create_table;
        list_tables;
        return;
    fi  

    if [[ $index -lt 0 ]]; then
        loading "Invalid option";
        list_tables;
        return;
    fi

    CURRENT_TABLE=${_tables[index - 1]}
    list_table_actions
    CURRENT_TABLE=""

    list_tables
}
