#!/bin/bash

list_table_actions() {
    local table_options=("List Data" "Insert New Record" "Update Record" "Delete Record" "Drop Table" "Return to Tables")

    title "table: $CURRENT_TABLE"

    print_menu "${table_options[@]}"

    read -p "# " type
    index=$(get_index table_options "$type")

    case $index in
        1) list_table_records ;;
        2) insert_table_records ;;
        3) update_table_records ;;
        4) delete_table_records ;;
        5) drop_table ;;
        6) return ;;
        *) loading "Invalid option, please try again" ;;
    esac

    list_table_actions
}
