#!/bin/bash

connect_db() {
    local databases=($(databases) "Return to Databases")

    title "Connect To DB"

    print_menu "${databases[@]}"

    read -p "# " option

    if [[ -z $option ]]; then
        loading "Invalid option"
        connect_db
    fi

    # Break loop
    if [[ $option -ge $((${#databases[@]})) || $option -lt 0 ]]; then
        return
    fi

    CURRENT_DB=${databases[option - 1]}
    list_tables
    CURRENT_DB=""

    connect_db
}
