#!/bin/bash

create_database() {

    title "Create New Database"
    read -p "name[0 to exit]: " dbname

    dbname="$(echo "$dbname" | sed 's/^ *//;s/ *$//')"  # trimg [start and end]


    if [[ "$dbname" == "0" ]]; then return; fi

    if [[ ! "$dbname" =~ ^[a-z]+$ ]]; then

        loading "Database name must contain only lowercase alphabetical letters"
    
        create_database ## Recall the function [ Recursion ]

        return
    fi


    local path="$STORAGE_PATH/$dbname"


    if [[ -d "$path" ]]; then
        loading "$Database Already exists"

        create_database ## Recall the function [ Recursion ]
        return
    fi

    mkdir -p "$path"
    
    loading "Database $dbname created successfully"
}