#!/bin/bash

detete_database() {
    local databases=($(databases) "Return to Main Menu")

    title "Delete Database"

    print_menu "${databases[@]}"

    read -p "# " option

    if [[ -z "$option" ]]; then loading "No Input Provided"; detete_database; return; fi

    index=$(get_index databases "$option")

    if [[ $index -eq ${#databases[@]} ]]; then return; fi  
    if [[ $index -lt 0 ]]; then loading "Invalid option"; detete_database; return; fi

    read -rp "Are you sure you want to delete ${databases[index-1]}? (y/n): " confirm

    if [[ "$confirm" =~ ^[Yy]$ ]]; then
        loading "${databases[index-1]} Is being deleted"

        rm -r $STORAGE_PATH/${databases[index-1]}

        if [[ $? -eq 1 ]]; then
            loading "failed to delete: ${databases[index-1]}"
        else
            loading "${databases[index-1]} Delete Successfully"
        fi
    else
        loading "Action Cancelled"
    fi
    detete_database
}