#!/bin/bash

list_databases() {
    local _databases="$(databases)"

    title "Display Databases"

    if [[ -z "$_databases" ]]; then
        loading "No databases found"
        return
    fi

    color_wrap yellow
        local count=1
        for db in $(databases); do
            echo "$count) $db"
            ((count++))
        done
    endwrap


    read -p "Back ..."
}