#!/bin/bash

insert_table_records(){
    local content=$(sed -n '$p' $(CURRENT_TABLE_DATA_PATH))  

    local columns=($(fetch_table_columns))

    declare -a newRecord

    local length="${#columns[@]}"
    local current=0



    title "Create New Record $CURRENT_TABLE in ($CURRENT_DB)"
    while (( current != length  )); do
        IFS=':' read -r column type pk <<< "${columns[$current]}"

        local default_value=""

        prompt="$column ($type)"
        
        local pk_value=""
        if [[ "$pk" == "primary_key" && "$type" == "int" ]]; then
            pk_value="$(get_latest_id)"
            prompt+=" [$pk_value]"
        fi

        read -p "$prompt : " default_value

        if [[ -z "$default_value" &&  ! -z "$pk_value" ]]; then
            default_value="$pk_value"
        fi


        if [[ "$type" == "int" ]] && ! is_valid_number "$default_value"; then
            error_loading "Value must be integer!"
            continue
        fi

        if [[ "$type" == "string" ]] && ! is_valid_string "$default_value"; then
            error_loading "Value is invalid: [alphanumeric spaces or  _,.-@#$&]"
            continue
        fi

        if [[ "$pk" == "primary_key" ]]; then
            pk_key="$(get_primary_key)"
            data=($(get_rows_by_keys "$pk_key:$default_value"))
            if [[ "${#data[@]}" -ne "0" ]]; then
                error_loading "Primary Key must be unique!"
                continue
            fi

        fi

        ((current++))

        newRecord+=("$default_value")
    done

    if (( length  != current )); then
        return
    fi

    success_loading "New Record Inserted (${newRecord[*]})"

    local old_IFS="$IFS"
    IFS=":"
    echo "${newRecord[*]}" >> $(CURRENT_TABLE_DATA_PATH)
    IFS="$old_IFS"
}
